src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Un autre utilisateur possède déjà cette email, merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom")
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Email(message="Veuillez renseigner une adresse email valide")
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmé votre mot de passe")
    */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Choice({"Particular", "Proffesional"})
     * @Assert\NotBlank(message="Vous devez choisir votre type de vente")
     */
    private $seller;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre adresse")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner le numero")
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner le code postal")
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner la ville")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre numero de tel")
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity=SaleCars::class, mappedBy="id_user", orphanRemoval=true)
     */
    private $id_cars;

    public function __construct()
    {
        $this->id_cars = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement s'il n'est pas fourni 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->FirstName.' '.$this->LastName.' '.rand());
        }
    }

    public function getFullName(){
        return "{$this->FirstName} {$this->LastName}";
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

     /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSeller(): ?string
    {
        return $this->seller;
    }

    public function setSeller(?string $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|SaleCars[]
     */
    public function getIdCars(): Collection
    {
        return $this->id_cars;
    }

    public function addIdCar(SaleCars $idCar): self
    {
        if (!$this->id_cars->contains($idCar)) {
            $this->id_cars[] = $idCar;
            $idCar->setIdUser($this);
        }

        return $this;
    }

    public function removeIdCar(SaleCars $idCar): self
    {
        if ($this->id_cars->removeElement($idCar)) {
            // set the owning side to null (unless already changed)
            if ($idCar->getIdUser() === $this) {
                $idCar->setIdUser(null);
            }
        }

        return $this;
    }
}

templates/partials/footer.html.twig
<div class="text-center bg-warning">
    <p>Copyright CarSale - &copy;EPSE - PWD - 2020/2021</p>
</div>
    

templates/partials/header.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-warning ps-3 pe-3">
    <a class="navbar-brand" href="{{ path('Accueil') }}"><img id="logo" src="../uploads/Logo site de vente voiture banner.png" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link active" href="{{ path('Accueil') }}">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('prosales_index') }}">Véhicules Professionnel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('partsales_index') }}">Véhicules Particulier</a>
            </li>
        </ul>
    
        <ul class="navbar-nav ms-auto">
            {% if app.user %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="accountDropdownLink">
                    <img src="/uploads/{{ app.user.picture }}" class="avatarmenu" alt=""> {{app.user.fullName}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="accountDropdownLink">
                        <a href="{{ path('adds_new') }}" class="dropdown-item">Créer une annonce</a>
                            <div class="dropdown-divider"></div>
                        <a href="{{ path('account_index') }}" class="dropdown-item">Mon compte</a>
                        <a href="#" class="dropdown-item">Mes annonces</a>
                        <a href="{{ path('account_profileModify') }}" class="dropdown-item">Modifer mon profil</a>
                            <div class="dropdown-divider"></div>
                        <a href="{{ path('account_logout') }}" class="dropdown-item">Déconnexion</a>
                    </div>
                </li>
            {% else %}
                <li class='nav-item'>
                    <a href="{{ path('account_register') }}" class="nav-link">Inscription</a>
                </li>
                <li class='nav-item'>
                    <a href="{{ path('account_login') }}" class="nav-link">Connexion</a>
                </li>
            {% endif %}     
        </ul>
    </div>
</nav>